### ISSUE TITLE
installing multiple versions of the same package

### ISSUE THREAD

**Issue by xgbuils** [maxleiko/npmi#22] opened 2018-08-18 15:13 UTC
Hi!

I'm creating a package that has the capacity to perform benchmarks between different packages and different versions of the same package. Then, I need to install packages dynamically and I need to install different versions of the same package.

I tried to use no public property `pkgName`, thinking that maybe was the destination directory name, but not. The destination directory is `node_module/lodash` and not `node_modules/lodash@4.7.10`

``` javascript
const npmi = require('npmi')
npmi({
    name: 'lodash',
    version: '4.17.10',
    pkgName: 'lodash@4.17.10'
}, (err, result) => {
    if (err) {
        console.log(err)
    }
    console.log('installed', result)
})
```
Then, is there a way to installing multiple versions of the same package?

Cheers!

**Comment by maxleiko** [comment] 2018-08-18 22:48
@xgbuils  You have to install each of them in a different directory, otherwise you'll overwrite them as you install another version of the same module.

```js
// something like this would do the trick
// as you would get a `node_modules` for each `lodash/{version}/node_modules`
npmi({ name: 'lodash', version: '4.17.10', path: '/lodash/4.17.10' }, ...);
npmi({ name: 'lodash', version: '4.17.9', path: '/lodash/4.17.9' }, ...);
```

As this is not a bug, I'll close the issue.

**Closed by maxleiko** 2018-08-18 22:48 UTC

**Comment by xgbuils** [comment] 2018-08-18 23:10
Thanks @maxleiko
